scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: [
          'host.docker.internal:9200',
        ]
        labels:
          service: 'prometheus-poc'
          group: 'development'
rule_files:
  - 'alert.rules'